[project]
name = "reset-bridge"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.bridge-core]
path = "contracts/bridge-core.clar"
depends_on = []

[contracts.bridge-vault]
path = "contracts/bridge-vault.clar"
depends_on = []

[contracts.bridge-access]
path = "contracts/bridge-access.clar"
depends_on = []

[contracts.bridge-validator]
path = "contracts/bridge-validator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
